<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN51013488" failures="1" tests="10" name="usertest" time="23.139" errors="0" timestamp="2024-07-07T23:29:48 IST">
  <testcase classname="api.TestCases.UserTestDataDriven" name="createUserTest" time="4.942"/>
  <testcase classname="api.TestCases.UserTestDataDriven" name="createUserTest" time="2.679"/>
  <testcase classname="api.TestCases.UserTestDataDriven" name="createUserTest" time="1.283"/>
  <testcase classname="api.TestCases.UserTestDataDriven" name="deleteUserTest" time="1.477"/>
  <testcase classname="api.TestCases.UserTestDataDriven" name="deleteUserTest" time="1.514"/>
  <testcase classname="api.TestCases.UserTestDataDriven" name="deleteUserTest" time="1.533"/>
  <testcase classname="api.TestCases.UserTests" name="createUserTest" time="1.361"/>
  <testcase classname="api.TestCases.UserTests" name="getUserTest" time="1.859"/>
  <testcase classname="api.TestCases.UserTests" name="updateUserTest" time="1.457">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.TestCases.UserTests.updateUserTest(UserTests.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- updateUserTest -->
  <testcase classname="api.TestCases.UserTests" name="deleteUserTest" time="1.273"/>
</testsuite> <!-- usertest -->
